### ISSUE TITLE
Can not install multiple instances of Calibre Web on YunoHost

### ISSUE THREAD

**Issue by alhuwile32768** [YunoHost-Apps/calibreweb_ynh#106]
Dear YunoHost Crew

First of all I want to thank you for the wonderful host-it-yourself-solution you are giving, I am using YunoHost since 2 years and am very amazed how well it worked. (As I never understood up to this moment how to set up multiple subdomains)

I have a little issue. On my Raspberry Pi 4 I am hosting an instance of Yunohost with a Calibre Web service, say library.domain.ch and now I want to add another Calibre Web service on it, say library.law.domain.ch.
The description of Calibre Library says "Multiple times installable: Yes" so I though cool, I can organize my library in that way using multiple instances.
The problem is now the following: When I try to install a second service/instance of Calibre-web I get multiple pip errors, which are cumbersome to decode.
https://paste.yunohost.org/raw/efehapuses

There some cryptography wheel is unable to install due to some unmet dependencies. Also I still didnt understand the concept of python virtual environments but the script suggests that one is generated. 

I would kindly appreciate any kind of help to solve this riddle, as it is a great pity not being able to use a second service law.library.domain.ch

**Comment by Krakinou** [comment]
Hello,
The issue is not linked to the multiple instance but rather a dependency issue. That's something I've been struggling with for a long time: Sometimes the pip3 program/dependency changes and things that were perfectly fine stop working for a few days/weeks, then work again...

Nevertheless I just tested on my test machine on Yunohost 11.0.9 and I could install without pb: On which debian/Yunohost version are you?

**Comment by alhuwile32768** [comment]
Thank you very much for the answer. Im sorry for responding rather late. The issue solved itself now by updating from debian 10 to debian 11. Now its possible to have multiple instances of Calibre-Web.
