### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by ahstro** [YunoHost-Apps/calibreweb_ynh#30]
This repo is currently [five releases](https://github.com/janeczku/calibre-web/releases) behind calibre-web, so it might be worth looking into updating it soon. Beware though, one of the releases has the warning: "**!Attention! Please backup all data before updating !Attention! Due to a bug in the auto updater, an update from a commit version before january 29th 2019 will lead to loss of all data**", so I'm not sure how we would go about this..

**Comment by Krakinou** [comment]
Yep, I know.
We're not using the auto updater (as a matter of fact, it's deactivated into the yunohost version)
The issue is that I did some nasty tricks to get the ldap working in the yunohost repo and I was hoping to get ldap properly working into the main release of calibre before releasing a new version for yunohost... but it's a little more complicated that it seems...
I'm still on the case, but I have not a lot of free time so the work is going very slowly...

**Comment by Krakinou** [comment]
Closed with #35
