### ISSUE TITLE
Impossible read ebooks online

### ISSUE THREAD

**Issue by silver74** [YunoHost-Apps/calibreweb_ynh#40]
Hello,

since the new version, its impossible to read online ebooks (epub) only download is now proposed. Before all works well.

Feature request: It's now possible to upload audiobooks and have it a audioplayer?

**Comment by Krakinou** [comment]
Hello,

It is possible that the update changes some settings on the database:
You can reactivate through the user settings:
![image](https://user-images.githubusercontent.com/9308214/82141153-33066580-9834-11ea-9a4b-1de550aa1c4f.png)

As per the audiobook, it should now be working since 0.6.6, but if you require it to work on some other way, you need to go to the app github itself: https://github.com/janeczku/calibre-web

**Comment by Krakinou** [comment]
No answer : closing
