### ISSUE TITLE
LDAP SSO does not work anymore

### ISSUE THREAD

**Issue by Krakinou** [YunoHost-Apps/calibreweb_ynh#62]
Since calibre-web code refactoring, single sign-on with yunohost does not work anymore, user has to re-authenticate

**Comment by thardev** [comment]
Hi @Krakinou

I managed to make it work again by uncommenting the `proxy_set_header        X-Remote-User           $remote_user;` line and setting the right values in `config_allow_reverse_proxy_header_login` and `config_reverse_proxy_login_header_name`.
Was this disabled because of a security issue?

Thanks!

**Comment by Krakinou** [comment]
Hello,
No, it was disabled because the upstream code evolved and I never had enough time to search how to re-enable it.
If you want, you can make a PR or send me the exact nginx config you're using, that would be great!

**Comment by thardev** [comment]
Thanks for your answer 😄 
After a bit more research, the solution that I propose works but only for non-public instances, because if we enable it for every instance it would be a security issue.
See: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#login-via-header-from-upstream-authentication-source
So I'll try to debug and check why the `Authorization` header auth doesn't work and see if I can fix it.

Regarding the changes for make it work in a non-public instance:

- Updating the `/var/www/calibreweb/app.db` with the following values:
  - `config_allow_reverse_proxy_header_login = 1`
  - `config_reverse_proxy_login_header_name = X-Remote-User`

- Updating `/etc/nginx/conf.d/foo.bar.d/calibreweb.conf`:
  - Uncomment the line `proxy_set_header X-Remote-User $remote_user;`
  
So for this repo those values have to be added to the [app-config_sql.py.patch.src](https://github.com/YunoHost-Apps/calibreweb_ynh/blob/master/sources/patches/app-config_sql.py.patch.src)
And to the [nginx.conf](https://github.com/YunoHost-Apps/calibreweb_ynh/blob/master/conf/nginx.conf)
But I guess some check has to be done in the install script to ensure that the instance is not public.

**Comment by Krakinou** [comment]
Ok, 
and also add some hook so that if the app is changed from public to private or vice versa by the admin, the parameters get updated in the nginx config file
Will look into it, thanks for the tip!

**Comment by thardev** [comment]
Hi again,

After a bit more research I found out that adding the following statement `login_user(user)` after this line:
https://github.com/janeczku/calibre-web/blob/1be7dfcdca7a3c9be08387dfa795f1d565ed266e/cps/usermanagement.py#L67
makes everything work fine back again with the `Authorization` header, no need to change anything on the config and I think it is more secure.
Should we apply a patch on this repo to the `usermanagement.py` file meanwhile I try and submit a PR to the Calibreweb repo so they maybe fix it? What do you think? :)

**Comment by Krakinou** [comment]
Hmm,
I don't think that's a good idea : according to the link you send:
_If using this feature, it's important that only the proxy is exposed to users, because if the Calibre-web instance is at all directly exposed to traffic, then a malicious user will be able to log in as any user that exists via simply setting a header._

And basically, what you propose is the same:  ````login_user(user)```` will login in any user providing it exists in the database.

I'm not an expert in such matters, but I think that as the proxy header login is not integrated with the LDAP (it's just an header from a web request) there is no way for now to automagically login if the app is made public.

**Comment by thardev** [comment]
Yes, but what I meant with the previous implementation it will only trigger `login_user(user)` after the user is validated with database/LDAP.
So the request will contain the `Authorization` header with `Bearer ${base64userpassword}` and if the credentials are right, then it will trigger the `login_user(user)`.
This approach I should only be used on public instances and should be secure.
There are a few issues I discovered when testing in my non-public instance with this approach (not sure if it applies for public as well):

- When you click logout button from Calibreweb interface you get redirected and are always logged in as the same user (basically you are stuck and cannot logout)
- If you go back to Yuno portal, logout from there, login as different user and click on Calibreweb app you'll be logged in as previous user (!). Then if you click logout from Calibreweb interface you'll be redirected and logged in as the current user.

Thanks a lot for the PR and the implementation :tada: 😄

**Comment by Krakinou** [comment]
_So the request will contain the Authorization header with Bearer ${base64userpassword} and if the credentials are right, then it will trigger the login_user(user)._
Are you sure about that, because for me header is not something that is encrypted, and base64 is not either. So anyone can send a request with the correct header and being log in.

I'm still working on the PR, but hopefully it will be ready soon! :)

**Comment by thardev** [comment]
Hi again 😄 

I'm no cybersec expert but I think that should be secure enough because header goes through HTTPS and you are sending credentials like in the same way you would do a login in a login page, as long as it goes through HTTPS everything should be fine.
So that is the intended behaviour, you should be able to send the `Authorization: Basic ${base64userpassword}` header and be able to login, that's how some API work.
I think for non-public instance we should completely avoid the `config_allow_reverse_proxy_header_login` but it should be safe to use the `Authorization: Basic`.

**Comment by Krakinou** [comment]
I guess we will have to wait a little bit before releasing, this issue is causing me trouble in the hook that change the nginx conf file:
https://github.com/YunoHost/issues/issues/1991

**Comment by eldertek** [comment]
Any update please ? 🥲

**Comment by eldertek** [comment]
![image](https://github.com/YunoHost-Apps/calibreweb_ynh/assets/118362885/bc5c303f-610f-484f-a6ab-6aa99eaae51d)
![image](https://github.com/YunoHost-Apps/calibreweb_ynh/assets/118362885/17cd5e93-8497-49ba-9ebe-1261a7aa6239)

This option and this nginx config make sso working.

If you don't have the time, I can try PR ?

**Comment by Krakinou** [comment]
Well, I don't have a lot of time but this is not the only things:
The nginx config itself works, but it require also that I change the way the authorization are given to the user to access the app, and I'm also working on moving on the v2 version of the package on multiple apps including calibreweb, which encounters some issues on the way.
I hope to close this issue for the next release of the app package, hopefully in a few weeks, maybe a little more

**Comment by Krakinou** [comment]
Closed in #130 
When app is private (not assigned to visitor group), SSO is now activated
When app is public, SSO is deactivated as recommended [here](https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#login-via-header-from-upstream-authentication-source)
Once upgraded, this may require to close and reopen the browser to work correctly.
