### ISSUE TITLE
Database error: (sqlite3.OperationalError) attempt to write a readonly database

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/calibreweb_ynh#71]
<img width="1379" alt="Screenshot 2021-04-02 at 11 48 30" src="https://user-images.githubusercontent.com/1538027/113405020-6b118b00-93a9-11eb-8570-47716f29845b.png">

This is just after a restore of calibre from backup.

Steps to reproduce:
1. Login to calibre web.
2. Click upload button and select book for upload. (tried 2: pdf and epub.)

**Comment by Krakinou** [comment]
Can you give the output of 
`ls -la /var/www/calibreweb/app.db`

**Comment by lightnin** [comment]
-rw-r--r-- 1 calibreweb calibreweb 98304 Mar  8 19:41 /var/www/calibreweb/app.db

**Comment by Krakinou** [comment]
OK, I successfully reproduced the error.
Will give it a look.

**Comment by Krakinou** [comment]
So, the issue is due to the fact that calibreweb user cannot access the folder where metadata.db and ebook files are located. This requirement is stated by a warning message by the restore script, but I guess I have to make it more talkative.
Moreover, as the access to `/home/yunohost.multimedia` is managed by acl instead of basic linux access right management, this make the point much less easy for basic users to correct : I need to correct this also for future version.

So, in your case, if you are restoring on a system where yunohost.multimedia is already created, you just need to run
````
usermod -a -G multimedia calibreweb
systemctl restart calibreweb
````
If you are on a fresh install, without this folder, I guess in that case your library is not in `yunohost.multimedia` and hence you need to give calibreweb user rw access **to the folder of the library as well as on the library files themselves**.
For example:
````
chown -R calibreweb: /path/to/library
````

**Comment by lightnin** [comment]
> So, the issue is due to the fact that calibreweb user cannot access the folder where metadata.db and ebook files are located. 

Interesting - but note that books in the collection are presented as normal in the interface, and can be downloaded as normal. My collection is in: /home/yunohost.multimedia/share/eBook

> So, in your case, if you are restoring on a system where yunohost.multimedia is already created, you just need to run
>usermod -a -G multimedia calibreweb
>systemctl restart calibreweb

Tried this and it worked beautifully. I wasn't aware of acl privs... (Finally, something to make linux privilege issues a little bit harder! :) )  But I can see finer grained privileges are necessary for yunohost systems. 

I'm not sure whether to close the issue or not - I'll leave it for you to decide @Krakinou 

Anyhow - thanks for all you are contributing to Yunohost, and for making it possible for me to host my ebook library for friends and family. I very much appreciate the work you are doing!

**Comment by Krakinou** [comment]
> Interesting - but note that books in the collection are presented as normal in the interface, and can be downloaded as normal
Yes, all users have a read authorization for `/home/yunohost.multimedia/share/whatever`, the issue was when trying to write something.

>I'm not sure whether to close the issue or not - I'll leave it for you to decide @Krakinou
I just push a patch to fix this issue so that the issue does not arise again, thanks for pointing it to me!

>Anyhow - thanks for all you are contributing to Yunohost, and for making it possible for me to host my ebook library for friends and family.
You're welcome, I really enjoyed doing it :)!
