### ISSUE TITLE
Library not updated - Permission issues ?

### ISSUE THREAD

**Issue by elbubar** [YunoHost-Apps/calibreweb_ynh#91]
### Yunhost CalibreWeb fresh install

- Hardware: *Kimsufi*
- YunoHost version: 4.3.4.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: Keeping Registrar MX Plan
- Using, or trying to install package version/branch: 0.96.14~ynh1

### Steps to reproduce

- Change permissions of /home/yunohost.multimedia/share/eBook to admin:admin
- Send all eBooks in the folder (Author/BookTitle/Book.epub & other docs)
- Change permissions of /home/yunohost.multimedia/share/eBook to nextcloud:nextcloud 
- (I had tried with calibreweb:calibreweb) no changes, but at least with nextcloud:nextcloud I can access the files via NextCloud external drive
- Upload of books activated
- When I open Calibre-web, there's no book displayed.

### Expected behavior

Seeing the books.

### Logs

No logs.

I assume it would be a permission issue, but I don't know how Calibre keeps a watch on the folder to add new items.

Any help would be appreciated.

All the best for 2022 !

**Comment by Krakinou** [comment]
Hello,

The nextcloud integration is only aimed at locally sync the library on a desktop, for example, where you can use the "standard" calibre software to use the same library as calibre-web.

You cannot add directly the book in the library folder : The library (as in "list of books") is stored in the file called metadata.db in the root of the library's folder along with all the required files (epub, kindle, etc) in their own folder. This folder should only be updated via calibre and/or calibre-web.
By adding a book via the calibre/calibre-web interface, the books files and folders are added into the library's folder AND the metadata.db file is updated.

As far as I know, both nexcloud and calibreweb user are part of the multimedia group and as such have access to this folder : you shouldn't need to tweak them to work (beside, the permission for this folder are maintained via setfacl, so be careful).

**Comment by elbubar** [comment]
Thanks Krakinou for your answer...

I'm not using Calibre on my laptop... I was expecting to have all my library online... I saw on the [Calibre-web FAQ](https://github.com/janeczku/calibre-web/wiki/FAQ) the following : 

`Mass add books

It's possible to upload several books at once by selecting more than one file. The limitation is the upload size of the Calibre-web internal server (several hundred megabyte). **Another possibility is via a normal shall script by watching a folder content.** _Prerequisites for the example below is an installed Calibre program_. The script has to be called regularly (cron job). The script watches for content in the supervised path, calls Calibre to add the files in the folder to the library and deletes the files in the last step from the source folder.

#!/bin/bash
if [ "$(ls -A [folder to watch] )" ]; then
     calibredb add -r "[folder to watch]" --library-path="[path to calibre library]"
     rm [folder to watch]/*
fi

Does it means that I should install Calibre on my server and then call the script above ? I'm not sure to fully understand the syntax of the script, what would it be if I would like to keep the books in the same folder ? Would this works : ?

#!/bin/bash
if [ "$(ls -A [folder to watch] )" ]; then
     calibredb add -r "/home/yunohost.multimedia/share/eBooks/" --library-path="/home/yunohost.multimedia/share/eBooks/"
fi

And last but not least... the permission for this folder are maintained via setfacl, **so be careful**. Looks like I wasn't, shall I do anything to revert to the correct permissions settings, or would setfacl do it for me on next reboot ?

Many many thanks for the time taken !

**Comment by Krakinou** [comment]
Yes, calibredb is an executable from the calibre desktop version. It may be complicated to install on a yunohost server especially if you use an headless server, where a lot of dependencies will be missing.
I don't know how it works, so I don't know if you script would work neither.
I would recommand using the mass upload of the calibre-web interface to upload multiple book.
For now, the limit is set at 500Mo (which is quite a few ebooks), but you can update it to whatever you want in the nginx config file ( in `/etc/nginx/conf.d/yourserver.d/calibreweb.conf`).
Then reload nginx with `sudo systemctl reload nginx.service`

**Comment by N-Upchurch** [comment]
I've been pulling my hair out trying to get this working. TLDR: it doesn't.

> #!/bin/bash if [ "$(ls -A [folder to watch] )" ]; then calibredb add -r "[folder to watch]" --library-path="[path to calibre library]" rm [folder to watch]/* fi
> 
> Does it means that I should install Calibre on my server and then call the script above ? 

**This was my approach:**
---
1. First, I wanted to download ebooks via bittorrent, keep them seeding, and have those books added to the Calibre database. Because I didn't want to  use the same folder for downloaded ebooks (see reason below) and my Calibre library, I edited the script like so:
``` bash            
#!/bin/bash
if [ "$(ls -A /home/yunohost.transmission/eBooks)" ]; then
calibredb add -r -m ignore "/home/yunohost.transmission/ebooks" --library-path="/home/yunohost.multimedia/share/eBook"
fi
```
I added the [-m flag](https://manual.calibre-ebook.com/generated/en/calibredb.html#cmdoption-calibredb-add-automerge) and removed the rm command because I don't want to delete the original files that I'm trying to seed.

>I'm not sure to fully understand the syntax of the script, what would it be if I would like to keep the books in the same folder ? Would this works : ?

This isn't recommended. Calibre has its own special directory structure and the recommendation is to never manage your library manually. 

2. I installed Calibre, saved that script somewhere on my system and created a CRON job set to run every ten minutes (as root):
```
> su -
> apt install calibre
> crontab -e
```
The crontab entry:
```
*/10 * * * * root /root/scripts/addBooks.sh
```

**What happened:**
---
I kept getting permissions errors, which made no sense because the script was being run as root. When attempting to run the `calibredb` command outside of the script, I got the following error:
```
Traceback (most recent call last):
  File "/usr/bin/calibredb", line 19, in <module>
    from calibre.db.cli.main import main
  File "/usr/lib/calibre/calibre/db/cli/main.py", line 12, in <module>
    from calibre.db.legacy import LibraryDatabase
  File "/usr/lib/calibre/calibre/db/legacy.py", line 19, in <module>
    from calibre.db.cache import Cache
  File "/usr/lib/calibre/calibre/db/cache.py", line 22, in <module>
    from calibre.customize.ui import (
  File "/usr/lib/calibre/calibre/customize/ui.py", line 18, in <module>
    from calibre.customize.builtins import plugins as builtin_plugins
  File "/usr/lib/calibre/calibre/customize/builtins.py", line 752, in <module>
    from calibre.devices.smart_device_app.driver import SMART_DEVICE_APP
  File "/usr/lib/calibre/calibre/devices/smart_device_app/driver.py", line 2044, in <module>
    from zeroconf import (BadTypeInNameException, _HAS_A_TO_Z,
ImportError: cannot import name '_HAS_A_TO_Z' from 'zeroconf' (/usr/lib/python3/dist-packages/zeroconf/__init__.py)
```
After some very puzzled Searxing, I found [this bug](https://bugs.launchpad.net/calibre/+bug/1936889) that makes the currrent Calibre Debian package, *presumably packaged in the Cretaceous period per Debian's usual modus operandi,* incompatible with the zeroconf version installed on up-to-date yunohost systems.

At this point, I thought 'Aha! Flatpak will save the day!' but I was soon let down when I could find no way to run `calibredb` with a Flatpak install of Calibre.

**Conclusion:**
---
So, the bad news is (unless I've done something stupid; this possibility should not be discounted) there's no automating the addition of ebooks from your machine to the Calibre-Web library on a Debian-based server. The good news is that we might be able to get this working in a few years time when Debian decides to update the Calibre package.

**Comment by N-Upchurch** [comment]
Turns out you totally can use the calibredb command with flatpak, like so: `flatpak run --command=calibredb com.calibre_ebook.calibre [arguments...]` (Thanks to [this comment](https://github.com/flathub/com.calibre_ebook.calibre/issues/25#issuecomment-544306359) for the info). 

That said, here's how to import books from elsewhere in your filesystem into Calibre-Web using the Calibre Flatpak on YunoHost:

1. [Install Flatpak](https://flatpak.org/setup/Debian)

2. Install Calibre Flatpak
`flatpak install calibre`

3. Write the following script and save it somewhere on your filesystem (_make sure it is executable_):
``` bash                            
#!/usr/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/var/lib/flatpak/exports/bin

if [ "$(ls -A [folder to watch])" ]; then
flatpak run --command=calibredb com.calibre_ebook.calibre add -r -m ignore "[folder to watch]" --library-path="[path to calibre library]"

#Uncomment the line below to delete old ebook files after import
#rm -rf [folder to watch]/*
fi
```

4. Add the CRON job:
``` bash
sudo crontab -e
```
Append: `*/10 * * * *  [path to script]`
(send command output to a log file if you like: `*/10 * * * *  [path to script] > [path/to/my/logfile.log]`)

This will add books to your database every ten minutes. Edit `*/10` in your crontab to some other number of minutes if you like. Larger numbers will mean you will be less bombarded with failure emails if something goes wrong. 

5. Profit.
